site_name: "Landers' Coast Player Guide"


plugins:
 - search
 - autorefs
 
nav:
  - Home: index.md
  - Atlas:
    - General: Atlas/General.md
    - Cities:
      - Camor: Atlas/Cities/Camor.md
      - Keyford (nee. Keford): Atlas/Cities/Keyford (nee. Keford).md
      - Litoria (nee. Litore): Atlas/Cities/Litoria (nee. Litore).md
      - Mewood: Atlas/Cities/Mewood.md
      - Mudhaven: Atlas/Cities/Mudhaven.md
      - Rockhold Keep: Atlas/Cities/Rockhold Keep.md
      - The Kefordian Crater: Atlas/Cities/The Kefordian Crater.md
    - POIs:
      - Ashgrove Range: Atlas/POIs/Ashgrove Range.md
      - Beorg Bay: Atlas/POIs/Beorg Bay.md
      - Fennrich Marsh: Atlas/POIs/Fennrich Marsh.md
      - The Glade: Atlas/POIs/The Glade.md
    - Villages:
      - Butterwick: Atlas/Villages/Butterwick.md
      - Deysham: Atlas/Villages/Deysham.md
      - Frelnam Village: Atlas/Villages/Frelnam Village.md
      - Frontier Village: Atlas/Villages/Frontier Village.md
      - Gladehaven: Atlas/Villages/Gladehaven.md
  - Encyclopedia:
    - Books and Items:
      - Celestial Shadows The Arcane Eclipse Effect And Ley Line Dynamics In A Binary Star System: Encyclopedia/Books and Items/Celestial Shadows The Arcane Eclipse Effect and Ley Line Dynamics in a Binary Star System.md
      - Lessons For Sensible Living Ix   The Underdark: Encyclopedia/Books and Items/Lessons for Sensible Living IX - The Underdark.md
      - Minor Items: Encyclopedia/Books and Items/Minor Items.md
      - Potion Of Borrowed Time: Encyclopedia/Books and Items/Potion of Borrowed Time.md
    - Cosmology and Divinity:
      - 0.0 Gods And Divinity - Overview: Encyclopedia/Cosmology and Divinity/0.0 - Gods and Divinity - Overview.md
      - Aranok, The Justicar: Encyclopedia/Cosmology and Divinity/Aranok, The Justicar.md
      - Asterius, The Consort: Encyclopedia/Cosmology and Divinity/Asterius, The Consort.md
      - Death (Deity): Encyclopedia/Cosmology and Divinity/Death (Deity).md
      - Eshendal, The Landsire: Encyclopedia/Cosmology and Divinity/Eshendal, the Landsire.md
      - Lunara, The Skyfire: Encyclopedia/Cosmology and Divinity/Lunara, the Skyfire.md
      - Serinus, The Elder: Encyclopedia/Cosmology and Divinity/Serinus, The Elder.md
      - The Lightbringer: Encyclopedia/Cosmology and Divinity/The Lightbringer.md
      - Thuranm, The Forgemaster: Encyclopedia/Cosmology and Divinity/Thuranm, The Forgemaster.md
      - Wormweaver The Usurper: Encyclopedia/Cosmology and Divinity/Wormweaver the Usurper.md
      - Zerekiel, The Conqueror: Encyclopedia/Cosmology and Divinity/Zerekiel, The Conqueror.md
      - 1.0   Cosmology: Encyclopedia/Cosmology and Divinity/1.0 - Cosmology.md
    - Factions:
      - Bard Colleges In Landers' Coast: Encyclopedia/Factions/Bard Colleges in Landers' Coast.md
      - Minor Houses In Keyford: Encyclopedia/Factions/Minor Houses in Keyford.md
      - Talespinner Society: Encyclopedia/Factions/Talespinner Society.md
      - The Fold: Encyclopedia/Factions/The Fold.md
      - Keyfordian Specific:
        - Alderbrook Enclave Shops And POIs: Encyclopedia/Keyfordian Specific/Alderbrook Enclave Shops and POIs.md
        - Arcanist'S Gambit: Encyclopedia/Keyfordian Specific/Arcanist's Gambit.md
        - Argentwind Trade House: Encyclopedia/Keyfordian Specific/Argentwind Trade House.md
        - Keyfordian Council: Encyclopedia/Keyfordian Specific/Keyfordian Council.md
        - Keyfordian Culture: Encyclopedia/Keyfordian Specific/Keyfordian Culture.md
        - The Wellington Family:
            - House Wellington: Encyclopedia/Keyfordian Specific/The Wellington Family/House Wellington.md
            - Lord Eiling'S Restoration Speech: Encyclopedia/Keyfordian Specific/The Wellington Family/Lord Eiling's Restoration Speech.md
            - The Wellington Quarter: Encyclopedia/Keyfordian Specific/The Wellington Family/The Wellington Quarter.md
            - House Representatives:
                - Lady Siaculas Wellington: Encyclopedia/Keyfordian Specific/The Wellington Family/House Representatives/Lady Siaculas Wellington.md
                - Lord Eiling Wellington: Encyclopedia/Keyfordian Specific/The Wellington Family/House Representatives/Lord Eiling Wellington.md
                - Lord Gorad Wellington: Encyclopedia/Keyfordian Specific/The Wellington Family/House Representatives/Lord Gorad Wellington.md
                - Master Eulus Wellington: Encyclopedia/Keyfordian Specific/The Wellington Family/House Representatives/Master Eulus Wellington.md
                - Master Felix Wellington: Encyclopedia/Keyfordian Specific/The Wellington Family/House Representatives/Master Felix Wellington.md
            - Wellington Quarter POIs:
                - Meridian Club: Encyclopedia/Keyfordian Specific/The Wellington Family/Wellington Quarter POIs/Meridian Club.md
                - The Criterion: Encyclopedia/Keyfordian Specific/The Wellington Family/Wellington Quarter POIs/The Criterion.md
                - The Gilded Lily: Encyclopedia/Keyfordian Specific/The Wellington Family/Wellington Quarter POIs/The Gilded Lily.md
                - The Grand Library: Encyclopedia/Keyfordian Specific/The Wellington Family/Wellington Quarter POIs/The Grand Library.md
                - The Silver Sceptre: Encyclopedia/Keyfordian Specific/The Wellington Family/Wellington Quarter POIs/The Silver Sceptre.md
                - Wellington Apothecary: Encyclopedia/Keyfordian Specific/The Wellington Family/Wellington Quarter POIs/Wellington Apothecary.md
                - Wellington Manor: Encyclopedia/Keyfordian Specific/The Wellington Family/Wellington Quarter POIs/Wellington Manor.md
                - Wellington Stables: Encyclopedia/Keyfordian Specific/The Wellington Family/Wellington Quarter POIs/Wellington Stables.md
                - Wellington'S Court: Encyclopedia/Keyfordian Specific/The Wellington Family/Wellington Quarter POIs/Wellington's Court.md
                - Wellington'S Gallery Of Fine Arts: Encyclopedia/Keyfordian Specific/The Wellington Family/Wellington Quarter POIs/Wellington's Gallery of Fine Arts.md
      - Litorian Specific:
        - Litorian Culture: Encyclopedia/Litorian Specific/Litorian Culture.md
      - Science:
        - Feybane: Encyclopedia/Science/Feybane.md
        - Igniflora: Encyclopedia/Science/Igniflora.md
        - Landers' Coast Gazetteer: Encyclopedia/Science/Landers' Coast Gazetteer.md
        - Technology In Landers' Coast: Encyclopedia/Science/Technology in Landers' Coast.md
        - The Lunar Eclipse: Encyclopedia/Science/The Lunar Eclipse.md
  - Meta:
    - Player Stuff: Meta/Player Stuff.md
